name: Generate Log

on:
  push:
    branches:
      - master

jobs:
  listar-archivos:
    runs-on: self-hosted
    steps:
      - name: Listar Archivos en el Servidor Local
        run: |
          pwd
          ls
  generate-log:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: CD
        run: cd /root/garfio
      - name: LS
        run: ls

      - name: Stop containers
        run: |
          docker-compose stop quoter
