name: Generate Log

on:
  push:
    branches:
      - master

jobs:
  generate-log:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cd
        run: cd /root/garfio

      - name: Stop containers
        run: |
          docker-compose stop social
