name: Generate Log

on:
  push:
    branches:
      - master

jobs:
  generate-log:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate log file
        run: |
          echo "$(date)" >> log.txt
